# Base ollama Runner Image
FROM ollama/ollama:latest

# Runing Port
EXPOSE 11434

# # Default QWEN 2.5 7B Model Install
# RUN ollama serve & \
#     sleep 5 && \
#     ollama pull qwen2.5:7b

# Exicute Command
CMD ["serve"]		
