pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps{
                checkout scm
            }
        }

        stage('Build Docker Image'){
            steps {
                sh "docker build -t llm-chat-service:${BUILD_NUMBER} ."
            }
        }
    }
}