apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chat

spec:
  type: ClusterIP

  selector:
    app: chat-service

  ports:
    - name: http
      port: 3080
      targetPort: 3080
      protocol: TCP
