apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: llm
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ollama

  template:
    metadata:
      labels:
        app: ollama

    spec:
      nodeSelector:
        ollama: "true"

      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 11434
              protocol: TCP

          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "4Gi"
