pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t llm-api-gateway:${BUILD_NUMBER} ."
            }
        }
    }
}
