server {
    listen 80;
    server_name _;

    # Health check
    location /health {
        return 200 "API Gateway is healthy\n";
        add_header Content-Type text/plain;
    }

    # Chat Service - exact /api/chats
    location = /api/chats {
        proxy_pass http://chat-service.chat.svc.cluster.local:3080/chats;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Chat Service - /api/chats/*
    location /api/chats/ {
        proxy_pass http://chat-service.chat.svc.cluster.local:3080/chats/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Ollama model list
    location = /api/tags {
    	proxy_pass http://ollama.llm.svc.cluster.local:11434/api/tags;

    	proxy_http_version 1.1;

    	proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	proxy_set_header X-Forwarded-Proto $scheme;
    }
}
